name = "LRESolve"
uuid = "ee29a0df-cd28-4477-a8c7-b2df1281527b"
authors = ["NormannR <normannrion@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
